add support for a second hard disk

diff --git a/quickemu b/quickemu
--- a/quickemu
+++ b/quickemu
@@ -265,6 +265,21 @@ function vm_boot() {
     fi
   fi
 
+  #i needed a second hard disk for stuffs... 
+  if [[ -n "${disk2_img}" ]]; then
+	if [[ ! -f "${disk2_img}" ]]; then
+	      mkdir -p "${VMDIR}" 2>/dev/null
+	      ${QEMU_IMG} create -q -f qcow2 "${disk2_img}" "${disk2}"
+	      if [ $? -ne 0 ]; then
+	    	  echo "ERROR! Failed to create ${disk2_img}"
+	          exit 1
+	      fi
+	fi
+    echo " - Disk(2):     ${disk2_img} (${disk2})"
+	drive2_cmd="-drive if=none,id=drive1,cache=directsync,aio=native,format=qcow2,file=${disk2_img}"
+	drive2_cmd="${drive2_cmd} -device virtio-blk-pci,drive=drive1,scsi=off ${STATUS_QUO}"
+	#echo "${drive2_cmd}"
+  fi
   # Has the status quo been requested?
   if [ "${STATUS_QUO}" == "-snapshot" ] &&  [ -z "${iso}" ]; then
     echo "             Existing disk state will be preserved, no writes will be committed."
@@ -475,6 +490,7 @@ function vm_boot() {
       -drive media=cdrom,index=1,file="${driver_iso}" \
       -drive if=none,id=drive0,cache=directsync,aio=native,format=qcow2,file="${disk_img}" \
       -device virtio-blk-pci,drive=drive0,scsi=off ${STATUS_QUO} \
+      ${drive2_cmd} \
       ${VIDEO} -display ${OUTPUT},gl=${GL}${OUTPUT_EXTRA} \
       -device qemu-xhci,id=usb,p2=8,p3=8 -device usb-kbd,bus=usb.0 -device usb-tablet,bus=usb.0 ${USB_PASSTHROUGH} \
       -device virtio-net,netdev=nic -netdev ${NET},id=nic \
@@ -533,7 +549,9 @@ img=""
 iso=""
 driver_iso=""
 disk_img=""
-disk="64G"
+disk2_img=""
+disk="24G"
+disk2="24G"
 usb_devices=()
 ram=""
 cpu_cores=""
